atlantashows/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('venues/', views.venues_index, name='venues_index'),
    path('venues/<int:venue_id>/', views.venues_detail, name='detail'),
    path('venues/create/', views.VenueCreate.as_view(), name='venues_create'),
    path('venues/<int:pk>/update/', views.VenueUpdate.as_view(), name='venues_update'),
    path('venues/<int:pk>/delete/', views.VenueDelete.as_view(), name='venues_delete'),
    path('venues/<int:venue_id>/add_shows/', views.add_shows, name='add_shows'),
    path('venues/<int:venue_id>/add_photo/', views.add_photo, name='add_photo'),
    path('acounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

class Venue(models.Model):
    name = models.CharField(max_length=100)
    loc = models.CharField(max_length=100)
    description = models.TextField(max_length=250)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'venue_id': self.id})


class Shows(models.Model):
    class Meta:
        ordering = ('-date',)

    date = models.DateField()
    band = models.CharField(max_length=30)
    cost = models.SmallIntegerField()

    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.band} on {self.date} for ${self.cost}'

class Photo(models.Model):
    url = models.CharField(max_length=200)
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for venue_id: {self.venue_id} @{self.url}'

main_app/forms.py
from django.forms import ModelForm
from .models import Shows

class ShowsForm(ModelForm):
    class Meta:
        model = Shows
        fields = ('date', 'band', 'cost')

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Venue, Photo
from .forms import ShowsForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

import boto3
import uuid

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'atlanta-shows-52'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def venues_index(request):
    venues = Venue.objects.all()
    return render(request, 'venues/index.html', {'venues': venues})

@login_required
def venues_detail(request, venue_id):
    venue = Venue.objects.get(id=venue_id)
    shows_form = ShowsForm()
    return render(request, 'venues/detail.html', {
        'venue': venue,
        'shows_form': shows_form
    })

@login_required
def add_shows(request, venue_id):
    print(request.POST)
    form = ShowsForm(request.POST)
    if form.is_valid():
        new_shows = form.save(commit=False)
        new_shows.venue_id = venue_id
        new_shows.save()
    return redirect('detail', venue_id=venue_id)

@login_required
def add_photo(request, venue_id):
    photo_file = request.FILES.get('photo-file')
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f'{S3_BASE_URL}{BUCKET}/{key}'
            photo = Photo(url=url, venue_id=venue_id)
            photo.save()
        except:
            print('An error occured uploading file')
    return redirect('detail', venue_id=venue_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

class VenueCreate(LoginRequiredMixin, CreateView):
  model = Venue
  fields = '__all__'
  success_url = '/venues/'

class VenueUpdate(LoginRequiredMixin, UpdateView):
  model = Venue
  fields = '__all__'

class VenueDelete(LoginRequiredMixin, DeleteView):
  model = Venue
  success_url = '/venues/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block title %}
About | Atlanta Shows
{% endblock %}
{% block content %}
<div class='meh'>
    <img src="../static/photo/img02.GIF" alt="meh" class="responsive-img">
</div>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper #262626 grey darken-4">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="center brand-logo">  Atlanta Shows</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'venues_create' %}">Add a Venue</a></li>
            <li><a href="{% url 'venues_index' %}">Venues</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer #262626 grey darken-4">
      <div class="center">
        All Rights Reserved, © 2022 Atlanta Shows  
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block title%}
Home | Atlanta Shows
{% endblock %}
{% block content %}
<div>
    <div class="center-align">
        <img src="../static/photo/img01.GIF" alt="meh" class="responsive-img">
    </div>
</div>
{% endblock %}

main_app/templates/main_app/venue_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Venue</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' venue.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/venue_form.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Venue</h1>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/venues/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Venue Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ venue.name }}</span>
        <p>Neighborhood: {{ venue.loc }}</p>
        <p>Description: {{ venue.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'venues_update' venue.id %}">Edit</a>
        <a href="{% url 'venues_delete' venue.id %}">Delete</a>
      </div>
    </div>
    {% for photo in venue.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form
      action="{% url 'add_photo' venue.id %}"
      enctype="multipart/form-data"
      method="POST"
      class="card-panel"
    >
      {% csrf_token %}
      <input type="file" name="photo-file" />
      <br /><br />
      <input type="submit" class="btn" value="Upload Photo" />
    </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_shows' venue.id %}" method="POST">
      {% csrf_token %}
      {{ shows_form.as_p }}
    <input type="submit" class="btn" value="Add Show" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Band</th>
          <th>Cost</th>
        </tr>
      </thead>
      <tbody>
        {% for show in venue.shows_set.all %}
        <tr>
          <td>{{ show.date }}</td>
          <td>{{ show.band }}</td>
          <td>${{ show.cost }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

main_app/templates/venues/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Venue List</h1>

{% for venue in venues %}
<div class="card">
  <a href="{% url 'detail' venue.id %}">
  <div class="card-content">
    <span class="card-title">{{ venue.name }}</span>
    <p>Neighborhood: {{ venue.loc }}</p>
    <p>Description: {{ venue.description }}</p>
  </div>
  </a>
</div>
{% endfor %}
{% endblock %}